### ISSUE TITLE
Google-News: feed.extract returns error

### ISSUE THREAD

**Issue by mittendo** [DataWookie/feedeR#1]
Dear Data Wookie, 

thank you for your work! 
I've tried to retrieve rss-feeds from Google News, but `feed.extract`  returns an error: 

`feed.extract("https://news.google.com/news?cf=all&hl=de&pz=1&ned=de&output=rss")`

returns: 

> Error in UseMethod("xmlAttrs", node) : 
>   nicht anwendbare Methode für 'xmlAttrs' auf Objekt der Klasse "NULL" angewendet. 

Best regards,

Volker

**Comment by DataWookie** [comment]
Hi Volker, thanks for the feedback. Just had a look at that feed and it's a beast! But it's precisely the kind of test case that I am looking for. Thank you! I will dig into what aspect is breaking the code shortly. I am off to teach a class now, but hopefully I will be able to revert with a solution later today. Best regards, Andrew.

**Comment by DataWookie** [comment]
Hi Volker, I think that I've resolved that issue. Two problems:

1. How URLs were being cleaned up.
2. Parsing of dates.

Should work for your case now. Happy RSS scraping! Best regards, Andrew.
