### ISSUE TITLE
Not able to parse Date from Cnbc RSS feeds.

### ISSUE THREAD

**Issue by gautamkrc** [DataWookie/feedeR#10]
Hi,

I am facing issue in parsing timestamp of Cnbc RSS feeds. please see below. I am also attaching the result of getUrl in a file as you had advised to my earlier issue.
[cnbc_business-news.txt](https://github.com/DataWookie/feedeR/files/763753/cnbc_business-news.txt)

Below Code is failing
-----------------------------------------------------------------
> feed.extract("http://www.cnbc.com/id/10001147/device/rss/rss.html")
Error: Unable to parse date.
In addition: Warning message:
All formats failed to parse. No formats found.

I am attaching the output from below code.
-------------------------------------------------------------------
library(RCurl)
xml = getURL("http://www.cnbc.com/id/10001147/device/rss/rss.html")
cat(xml, file = "cnbc_business-news.xml")

Email ID: gautamk2017@email.iimcal.ac.in

**Comment by DataWookie** [comment]
Added another date format to handle this feed. Tested. Should be good now.
