### ISSUE TITLE
RSS without date

### ISSUE THREAD

**Issue by YonghuiDong** [DataWookie/feedeR#14]
Hi,
I am playing feedR package, and I encountered the following error:

```r
a <- feed.extract("http://feeds.nature.com/nplants/rss/current")
```
> Error in if (is.na(parsed)) stop("Unable to parse date.", call. = FALSE) :    argument is of length zero

I think the reason is due to the fact that some RSS feeds do not provide date. I have found that many RSS feeds for scientific journals do not contain date. 

Are there some suggestions to deal with this problem? Thanks a lot.

**Comment by DataWookie** [comment]
Hi,

I have pushed some changes which should address this issue. Please install again from GitHub. Let me know if you still have problems.

Thanks,
Andrew.

**Comment by YonghuiDong** [comment]
Thanks a lot. It works now
