### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by YonghuiDong** [datawookie/feedeR#15]
Thanks for the nice package. The current feedeR version exports Title, Dates and Links, it will be great if it can export (partial) **Contents** as well.

**Comment by datawookie** [comment]
Hi @YonghuiDong, sorry for the delay in getting back to you on this. Can you please give me more specifics of what you have in mind? Perhaps point me to a feed and let me know what data you would like to get back? What do you mean by "partial" contents? How would you like to specify what portion of the contents you get back? Thanks, Andrew.

**Comment by YonghuiDong** [comment]
Thanks for your kind help. I would also like to fetch part of the contents from the link as well, not e.g., the first 200 words of the contents from the link. 

Current `feedeR` version only export title, date and link from Rss feed.
feedeR:: feed.extract("https://feeds.feedburner.com/RBloggers")

The R package [scifetch](https://github.com/yufree/scifetch) can export contents as well, but it does not support RSS feeds of scientific journals very well.
scifetch::getrss("https://feeds.feedburner.com/RBloggers")

Therefore I am wondering if `feedeR` can do the similar job.

**Comment by datawookie** [comment]
> The probeem with `scifetch` is that it does not supports RSS feeds of scientific journals very well.

Understood.

Just so that I have an idea of what you are wanting to achieve, please can you point me to some examples of relevant "RSS feeds of scientific journals" and give me an idea of what you'd be looking for in the output.

**Comment by datawookie** [comment]
Hi @YonghuiDong , I've added the description field to the RSS output. Changes are in the `dev` branch. Can you please test and let me know if that does what you want? Thanks, Andrew.

**Comment by YonghuiDong** [comment]
@datawookie Amazing, Thanks a lot Andrew!

I have tested the RSS of RBloggers, and the result is exactly what I need.

    feedeR:: feed.extract("https://feeds.feedburner.com/RBloggers")

<img width="806" alt="Screen Shot 2020-04-13 at 14 06 47" src="https://user-images.githubusercontent.com/22663189/79116018-07551300-7d90-11ea-87f3-15cff7663e27.png">

However, when I test the scientific journal, e.g. Nature Plants, the description are all NAs. 

    feed.extract("http://feeds.nature.com/nplants/rss/current")

<img width="800" alt="Screen Shot 2020-04-13 at 14 02 58" src="https://user-images.githubusercontent.com/22663189/79116107-46836400-7d90-11ea-90cc-4967d15cacc8.png">

Here is the RSS feed of Nature Plants: http://feeds.nature.com/nplants/rss/current. You can see from the link that there is a short summary for each article. 

Below is an example of the output from `feedly.com`. The summary of the article is also included.

<img width="749" alt="Screen Shot 2020-04-13 at 14 19 38" src="https://user-images.githubusercontent.com/22663189/79116735-ee4d6180-7d91-11ea-8c48-b91e3be8f0f5.png">

Is it possible that `feedeR` can fetch the summary as well?

Many scientific journals are non-open access journals, which require subscriptions. But the abstract of each article is available. **It will be even better** if `feedeR` can fetch the abstract of the article.

Thanks a lot again.

Yonghui

**Comment by datawookie** [comment]
> However, when I test the scientific journal, e.g. Nature Plants, the description are all NAs.

Yes, that's because it's an RDF feed and I implemented the fix for an RSS feed (based on the fact that the original example you provided me with was https://feeds.feedburner.com/RBloggers).

**Comment by datawookie** [comment]
I've pushed updates for RDF feed to the `dev` branch. Please test and let me know.

**Comment by YonghuiDong** [comment]
@datawookie Hi Andrew,

I have tested several different journals, this version works very well. Thanks a lot!!

Yonghui

**Comment by datawookie** [comment]
Great. I'll merge into the `master` branch once I hear back on the other pending issue.
