### ISSUE TITLE
locale de_DE.UTF-8: feed.extract parse date error

### ISSUE THREAD

**Issue by mittendo** [DataWookie/feedeR#2]
Dear Andrew,

thank you for working so fast! Feed extract works fine on my server now.

However, when I'm working on my Desktop (with Locale de_DE.UTF-8), feed.extract() throws an error:

> Fehler: Unable to parse date

If I manually set 
`Sys.setlocale("LC_TIME", "C")  `

`feed.extract("https://news.google.com/news?cf=all&hl=de&pz=1&ned=de&output=rss&q=buergerbegehren")`

works fine. 

With the desktop locale it won't work.

`Sys.getlocale("LC_ALL")`

  
>  [1] "LC_CTYPE=de_DE.UTF-8;LC_NUMERIC=C;LC_TIME=de_DE.UTF-8;LC_COLLATE=de_DE.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=de_DE.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=C"

I think, your Package can be very useful for many people, if it can handle I18n issues.

All the best

Volker

**Comment by DataWookie** [comment]
Hi Volker,

Thanks for the further feedback. At least I know that one person is using this package. :)

I'll take a look at this issue after I'm done teaching today. Some of my collaborators, who work in a Korean locale, have had similar issues recently when using `rvest`. I found a work around for those. Hopefully something similar can be applied here.

Best regards, Andrew.

**Comment by mittendo** [comment]
Hi Andrew,

a quick and dirty workaround, that is doing the job for me is attached 
(not a good coding standard, I know ...).

I set LC_TIME to "C" immediately, before strptime occurs and set it back 
to original afterwards.


parse.date <- function(date) {
   FORMATS = c(
     "%a, %d %b %Y %H:%M:%S %z", # Fri, 05 Aug 2016 13:28:00 +0000
     "%Y-%m-%dT%H:%M:%S %z"      # 2016-07-23T06:16:08-07:00
   )
   #
   # Transform time zone codes.
   #
   date = sub("GMT$", "+0000", date)
   #
   # Fix time zone offset: insert space before and remove colon.
   #
   date = 
sub("(?<=[^[:blank:]])([+-])([[:digit:]]{2}):?([[:digit:]]{2})$", " 
\\1\\2\\3", date, perl = TRUE)
   #

   ## Workaround for Internationalization issues:
   localeTmp <- Sys.getlocale("LC_TIME")
   Sys.setlocale("LC_TIME", "C")

   for (fmt in FORMATS) {
     parsed <- strptime(date, fmt, tz = "UTC")
     #
     if (!is.na(parsed)) return(as.POSIXct(parsed))
   }
   stop("Unable to parse date.", call. = FALSE)

   ## Set locale back to original state

   Sys.setlocale("LC_TIME", locale = localeTmp)
}


Best regards

Volker

Am 11.08.2016 um 13:29 schrieb Andrew Collier:

**Comment by DataWookie** [comment]
Hi Volker, that does indeed do the job. However, my understanding is that once the locale has been changed in a given R session via Sys.setlocale() it cannot be changed back again. So this solution may have unintended side effects. I have a solution which applies a temporary change in locale. I'll send it to you for trial. Thanks, Andrew.

**Comment by DataWookie** [comment]
Hi Volker, I sent you an updated copy of the package yesterday. Did that resolve the parsing issue? Thanks, Andrew.

**Comment by mittendo** [comment]
Hi Andrew,

Yes, this update did it! Thank you for your effort!

Best regards,

Volker

Am Freitag, 12. August 2016 08:29:55 CEST schrieb Andrew Collier 
<notifications@github.com>:
> Hi Volker, I sent you an updated copy of the package yesterday. 
> Did that resolve the parsing issue? Thanks, Andrew.
> 



-- 
Mit Dekko von meinem Ubuntu-Gerät gesendet

**Comment by DataWookie** [comment]
Great. Thanks, Volker. Those changes have been merged into the master branch. Have a good weekend.
