### ISSUE TITLE
Unable to feed.extract slashdot.com feed

### ISSUE THREAD

**Issue by erpreciso** [DataWookie/feedeR#4]
Get an error with this [/. (slashdot)](http://rss.slashdot.org/Slashdot/slashdot) feed
```
> library(feedeR)
> feed.extract("http://rss.slashdot.org/Slashdot/slashdot")
Error in UseMethod("xmlAttrs", node) : 
  no applicable method for 'xmlAttrs' applied to an object of class "NULL"
```
R version:
```
R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```
Trying to debug, I copied and pasted your package code in a R script, and it works properly by issuing the same command.

**Comment by DataWookie** [comment]
Hi!

Just tried

> feed.extract("http://rss.slashdot.org/Slashdot/slashdot")

using the development (GitHub) version of feedeR and it worked fine. Are you working with the CRAN version? If so, would you mind installing the version from GitHub and trying again? If that resolves your problem (and I'm pretty sure it will...) then I'll update the version on CRAN.

Thanks,
Andrew.

**Comment by erpreciso** [comment]
Hi, I was using the CRAN version. Just installed from GitHub and confirm it is working properly.
Thanks a lot for the helpful package, -- Stefano

**Comment by DataWookie** [comment]
Great. I'll update CRAN.
