### ISSUE TITLE
feed.extract() is failing with reuters finance RSS feed. Please see below the error.

### ISSUE THREAD

**Issue by gautamkrc** [DataWookie/feedeR#9]
Hi,

the feed.extract is giving an issue with the below URL as of now. Please help.

feed.extract("http://feeds.reuters.com/reuters/financialsNews")
Entity 'ldquo' not defined
Entity 'rdquo' not defined
Opening and ending tag mismatch: div line 60 and body
Opening and ending tag mismatch: body line 59 and html
Premature end of data in tag html line 1
Error: 1: Entity 'ldquo' not defined
2: Entity 'rdquo' not defined
3: Opening and ending tag mismatch: div line 60 and body
4: Opening and ending tag mismatch: body line 59 and html
5: Premature end of data in tag html line 1
Entity 'ldquo' not defined
Entity 'rdquo' not defined
Opening and ending tag mismatch: div line 60 and body
Opening and ending tag mismatch: body line 59 and html
Premature end of data in tag html line 1
Error: 1: Entity 'ldquo' not defined
2: Entity 'rdquo' not defined
3: Opening and ending tag mismatch: div line 60 and body
4: Opening and ending tag mismatch: body line 59 and html
5: Premature end of data in tag html line 1

Mail ID: gautamk2017@email.iimcal.ac.in

**Comment by DataWookie** [comment]
I don't seem to be able to open that feed. Please save the contents of the feed to a file and send it to me.

![image](https://cloud.githubusercontent.com/assets/6134409/22736776/963e6fe6-ee08-11e6-8421-aa3c222af79c.png)

**Comment by gautamkrc** [comment]
Hi ,

sorry, this is an issue with feed itself. this feed normally works fine. but today it has an issue. Apologies to raise a incorrect issue.
